### ISSUE TITLE
Where can find functions4models.py?

### ISSUE THREAD

**Issue by wanqiangdehuoguo** [JaredJGartner/SB_neoantigen_Models#3]
Hallo, I am currently working with the SB_neoantigen_Models and following the instructions provided in the instructions.txt file to run the model. According to the instructions, it says in line 70:

```
##unzip model and Edit functions4models.py in
cd SB_neoantigen_Models/src/models/
gunzip mmp_Model.pickle.gz
gunzip nmer_Model.pickle.gz
#Used text editor to change the paths to locations of IEDB Immunogenicity (beside to use .py3 file), and netmhcstabpan 
#immuno_loc = '/Users/gartnerjj/Desktop/SB_neoantigen_Models/src/immunogenicity/predict_immunogenicity.py3'
#netstab = '/Users/gartnerjj/Desktop/SB_neoantigen_Models/src/NetMHCStabpan1.0/netMHCstabpan-1.0/netMHCstabpan'
```
However, after cloning the project, I couldn't find the **functions4models.py** file in the **SB_neoantigen_Models/src/models** directory.

Could you please let me know where I can find this file or if it might be located elsewhere?

**Comment by JaredJGartner** [comment]
Sorry that should read prediction_models.py.  You need to change the path
in lines 30 and 32 in that file

**Comment by wanqiangdehuoguo** [comment]
Ok，thanks， i have already notice prediction_models.py in src.
